### ISSUE TITLE
Commands spawning Entity doesnt seem to work.

### ISSUE THREAD

**Issue by zwazel** [jarkonik/bevy_scriptum#4]
Hi I really like this plugin! It allowed me to very quickly add basic scripting support to my project, appreciate all the hard work!

**Describe the bug**
I encountered a bug where I tried to spawn an entity via script. for this i simply created a function, something like this:
```rust
fn spawn_modded_entity(
    mut commands: Commands,
) {
    commands.spawn(Name::new("ModdedEntity"));
}
```
And if I then call this via script, it indeed spawns an entity, but it has no components (in this case it should have a Name component, See screenshots below).
commands.entity(entity).insert() also doesnt seem work.

I'm not sure if this is a bevy or scriptum problem, but i tried to also call the same function as a normal bevy system and there it works fine.

**To Reproduce**
1. Spawn an entity with a script, this script should call a rust function in which you spawn a very simple entity with at least one component.
1. start the game
2. check if entity has the specified components

**Expected behavior**
It to spawn an entity with all the specified components.

**Screenshots**
![image](https://github.com/jarkonik/bevy_scriptum/assets/42088586/8d209923-dd7b-483c-94c2-c5bc0fd6bca2)

**Desktop (please complete the following information):**
 - OS: [Windows]

**Additional context**
I was able to work around this by making the functon send out a bevy event which then runs a system in which the entity gets spawned. but i would like to be able to instantly return the id of the entity to keep using it via scripts, and with this workaround i won't be able to do so.

**Comment by jarkonik** [comment]
Hi :wave:   I'm really glad you've been enjoying working with bevy_scriptum. I believe I've been able to fix the issue you've been experiencing and I'll be publishing a new release that will include the fix shortly.
